# Generated by Django 5.2.1 on 2025-07-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Order of the concept in the course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='lms.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
